version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html/DESSO
        ports: 
            - 8080:80
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test
    mysql:
        container_name: mysql-db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: test
        ports:
            - "9906:3306"
